# Generated by Django 5.1.3 on 2024-11-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permission_alter_role_description_rolepermissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(help_text='Comma-separated list of permissions'),
        ),
    ]
